/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FouetteSideDrawer {
        "email": string;
        "extra": string;
        "footer": string;
        "header": string;
        "open": () => Promise<void>;
        "opened": boolean;
        "phone": string;
    }
}
declare global {
    interface HTMLFouetteSideDrawerElement extends Components.FouetteSideDrawer, HTMLStencilElement {
    }
    var HTMLFouetteSideDrawerElement: {
        prototype: HTMLFouetteSideDrawerElement;
        new (): HTMLFouetteSideDrawerElement;
    };
    interface HTMLElementTagNameMap {
        "fouette-side-drawer": HTMLFouetteSideDrawerElement;
    }
}
declare namespace LocalJSX {
    interface FouetteSideDrawer {
        "email"?: string;
        "extra"?: string;
        "footer"?: string;
        "header"?: string;
        "opened"?: boolean;
        "phone"?: string;
    }
    interface IntrinsicElements {
        "fouette-side-drawer": FouetteSideDrawer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fouette-side-drawer": LocalJSX.FouetteSideDrawer & JSXBase.HTMLAttributes<HTMLFouetteSideDrawerElement>;
        }
    }
}
