/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FouetteCloseButton {
    }
    interface FouetteLogo {
        "image": string;
        "link": string;
    }
    interface FouetteSideDrawer {
        "email": string;
        "extra": string;
        "footer": string;
        "header": string;
        "link": string;
        "opened": boolean;
        "phone": string;
    }
    interface FouetteSideDrawerPanel {
        "panelTitle": string;
    }
}
declare global {
    interface HTMLFouetteCloseButtonElement extends Components.FouetteCloseButton, HTMLStencilElement {
    }
    var HTMLFouetteCloseButtonElement: {
        prototype: HTMLFouetteCloseButtonElement;
        new (): HTMLFouetteCloseButtonElement;
    };
    interface HTMLFouetteLogoElement extends Components.FouetteLogo, HTMLStencilElement {
    }
    var HTMLFouetteLogoElement: {
        prototype: HTMLFouetteLogoElement;
        new (): HTMLFouetteLogoElement;
    };
    interface HTMLFouetteSideDrawerElement extends Components.FouetteSideDrawer, HTMLStencilElement {
    }
    var HTMLFouetteSideDrawerElement: {
        prototype: HTMLFouetteSideDrawerElement;
        new (): HTMLFouetteSideDrawerElement;
    };
    interface HTMLFouetteSideDrawerPanelElement extends Components.FouetteSideDrawerPanel, HTMLStencilElement {
    }
    var HTMLFouetteSideDrawerPanelElement: {
        prototype: HTMLFouetteSideDrawerPanelElement;
        new (): HTMLFouetteSideDrawerPanelElement;
    };
    interface HTMLElementTagNameMap {
        "fouette-close-button": HTMLFouetteCloseButtonElement;
        "fouette-logo": HTMLFouetteLogoElement;
        "fouette-side-drawer": HTMLFouetteSideDrawerElement;
        "fouette-side-drawer-panel": HTMLFouetteSideDrawerPanelElement;
    }
}
declare namespace LocalJSX {
    interface FouetteCloseButton {
        "onClose"?: (event: CustomEvent<any>) => void;
    }
    interface FouetteLogo {
        "image"?: string;
        "link"?: string;
    }
    interface FouetteSideDrawer {
        "email"?: string;
        "extra"?: string;
        "footer"?: string;
        "header"?: string;
        "link"?: string;
        "opened"?: boolean;
        "phone"?: string;
    }
    interface FouetteSideDrawerPanel {
        "onOpenDrawer"?: (event: CustomEvent<any>) => void;
        "panelTitle"?: string;
    }
    interface IntrinsicElements {
        "fouette-close-button": FouetteCloseButton;
        "fouette-logo": FouetteLogo;
        "fouette-side-drawer": FouetteSideDrawer;
        "fouette-side-drawer-panel": FouetteSideDrawerPanel;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fouette-close-button": LocalJSX.FouetteCloseButton & JSXBase.HTMLAttributes<HTMLFouetteCloseButtonElement>;
            "fouette-logo": LocalJSX.FouetteLogo & JSXBase.HTMLAttributes<HTMLFouetteLogoElement>;
            "fouette-side-drawer": LocalJSX.FouetteSideDrawer & JSXBase.HTMLAttributes<HTMLFouetteSideDrawerElement>;
            "fouette-side-drawer-panel": LocalJSX.FouetteSideDrawerPanel & JSXBase.HTMLAttributes<HTMLFouetteSideDrawerPanelElement>;
        }
    }
}
